# Generated by Django 4.2 on 2025-03-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Borne",
        ),
        migrations.DeleteModel(
            name="Council",
        ),
    ]
