# Generated by Django 4.2 on 2025-03-14 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Map", "0002_delete_borne_delete_council"),
    ]

    operations = [
        migrations.CreateModel(
            name="Council",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("departement", models.CharField(max_length=30)),
                ("region", models.CharField(max_length=30)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Borne",
            fields=[
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "matricule",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("lat", models.CharField(max_length=20)),
                ("lon", models.CharField(max_length=20)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "council",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Map.council",
                    ),
                ),
            ],
        ),
    ]
