# Generated by Django 4.2 on 2025-03-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borne",
            name="lat",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="borne",
            name="lon",
            field=models.CharField(max_length=25),
        ),
    ]
