# Generated by Django 4.2 on 2025-03-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0004_alter_borne_lat_alter_borne_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="borne",
            name="place_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
