# Generated by Django 4.2 on 2025-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Map", "0005_borne_place_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="borne",
            name="reseau",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
